services:
  database:
    image: postgres:16
    container_name: database
    environment:
      POSTGRES_USER: sreuser
      POSTGRES_PASSWORD: srepass
      POSTGRES_DB: appdb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d:ro
    networks: [sre_net]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h localhost -p 5432",
        ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  backend:
    build: ./backend
    container_name: backend
    environment:
      DATABASE_URL: postgres://sreuser:srepass@database:5432/appdb?sslmode=disable
    networks: [sre_net]
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: frontend
    networks: [sre_net]
    depends_on: [backend]
    ports:
      - "80:80"

networks:
  sre_net:

volumes:
  db_data:
